function J = const_jacobian(in1)
%CONST_JACOBIAN
%    J = CONST_JACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Dec-2020 01:17:01

J = reshape([1.0,0.0,0.0,1.0,-7.0./1.0e+2,0.0,0.0,0.0,0.0,0.0],[2,5]);
