function phi = ground_const(in1)
%GROUND_CONST
%    PHI = GROUND_CONST(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Dec-2020 01:17:01

th0 = in1(8,:);
xw = in1(6,:);
yw = in1(7,:);
phi = [th0.*(-7.0./1.0e+2)+xw;yw-7.0./1.0e+2];
