function G = pseudo_convert(in1)
%PSEUDO_CONVERT
%    G = PSEUDO_CONVERT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Dec-2020 15:30:43

th2 = in1(10,:);
th3 = in1(11,:);
th4 = in1(12,:);
t2 = sin(th3);
t3 = -th4;
t4 = 1.0./t2;
t5 = t3+th2+th3;
t6 = sin(t5);
G = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4.*t6.*(1.93e+2./1.88e+2),t4.*(t6.*9.3e+1+sin(t3+th2).*1.88e+2).*(-1.103866392129947e-2),1.0],[7,5]);
