function T2Eq = GravityCompT2(Fdx,Fdy,d2,g,l1,l2,m2,th1,th2,thdot1)
%GravityCompT2
%    T2Eq = GravityCompT2(Fdx,Fdy,D2,G,L1,L2,M2,TH1,TH2,THDOT1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-01-12 11:17:45

t2 = th1+th2;
t3 = sin(t2);
T2Eq = Fdy.*l2.*t3+Fdx.*l2.*cos(t2)-d2.*g.*m2.*t3+d2.*l1.*m2.*thdot1.^2.*sin(th2);
end
