function out1 = eq_search_fixed_torque(in1)
%EQ_SEARCH_FIXED_TORQUE
%    OUT1 = EQ_SEARCH_FIXED_TORQUE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-01-08 18:03:07

k_ang = in1(6,:);
kspring = in1(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
u0 = in1(7,:);
u3 = in1(8,:);
t2 = sin(th3);
t3 = th1+th2;
t4 = th1+th4;
t5 = th2+th3;
t8 = -th4;
t10 = pi./4.0;
t6 = sin(t3);
t7 = sin(t4);
t9 = 1.0./t2;
t11 = t8+th2;
t13 = t5+t8;
t15 = t3+t10+th3;
t12 = sin(t11);
t14 = sin(t13);
t16 = sin(t15);
t19 = t6.*2.950848;
t20 = t7.*9.46665e-2;
t17 = t12.*1.88e+2;
t18 = t14.*9.3e+1;
t21 = t16.*7.3575e-1;
t22 = t17+t18;
out1 = [u0;t19+t20+t21+u0+sin(th1).*3.63951;t20+t9.*t14.*(t19+t21+(kspring.*(k_ang.*2.0-th2.*2.0))./2.0).*(1.93e+2./1.88e+2)-t9.*t16.*t22.*8.121696980096088e-3-t9.*t22.*u3.*1.103866392129947e-2;cos(t5).*(-9.3e+1./1.0e+3)-cos(th2).*(4.7e+1./2.5e+2)+cos(th4).*(1.93e+2./1.0e+3)+1.0./2.0e+1;sin(t5).*(-9.3e+1./1.0e+3)-sin(th2).*(4.7e+1./2.5e+2)+sin(th4).*(1.93e+2./1.0e+3)];
end
