// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controlCommand.proto

#include "controlCommand.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace stoupentoPlugin_msgs {
namespace msgs {
class ControlCommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ControlCommand>
      _instance;
} _ControlCommand_default_instance_;
}  // namespace msgs
}  // namespace stoupentoPlugin_msgs
namespace protobuf_controlCommand_2eproto {
static void InitDefaultsControlCommand() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::stoupentoPlugin_msgs::msgs::_ControlCommand_default_instance_;
    new (ptr) ::stoupentoPlugin_msgs::msgs::ControlCommand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::stoupentoPlugin_msgs::msgs::ControlCommand::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ControlCommand =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsControlCommand}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ControlCommand.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::stoupentoPlugin_msgs::msgs::ControlCommand, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::stoupentoPlugin_msgs::msgs::ControlCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::stoupentoPlugin_msgs::msgs::ControlCommand, u0l_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::stoupentoPlugin_msgs::msgs::ControlCommand, u3l_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::stoupentoPlugin_msgs::msgs::ControlCommand, u0r_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::stoupentoPlugin_msgs::msgs::ControlCommand, u3r_),
  0,
  1,
  2,
  3,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::stoupentoPlugin_msgs::msgs::ControlCommand)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::stoupentoPlugin_msgs::msgs::_ControlCommand_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "controlCommand.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024controlCommand.proto\022\031stoupentoPlugin_"
      "msgs.msgs\"D\n\016ControlCommand\022\013\n\003u0l\030\001 \002(\001"
      "\022\013\n\003u3l\030\002 \002(\001\022\013\n\003u0r\030\003 \002(\001\022\013\n\003u3r\030\004 \002(\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 119);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "controlCommand.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_controlCommand_2eproto
namespace stoupentoPlugin_msgs {
namespace msgs {

// ===================================================================

void ControlCommand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ControlCommand::kU0LFieldNumber;
const int ControlCommand::kU3LFieldNumber;
const int ControlCommand::kU0RFieldNumber;
const int ControlCommand::kU3RFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ControlCommand::ControlCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_controlCommand_2eproto::scc_info_ControlCommand.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:stoupentoPlugin_msgs.msgs.ControlCommand)
}
ControlCommand::ControlCommand(const ControlCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&u0l_, &from.u0l_,
    static_cast<size_t>(reinterpret_cast<char*>(&u3r_) -
    reinterpret_cast<char*>(&u0l_)) + sizeof(u3r_));
  // @@protoc_insertion_point(copy_constructor:stoupentoPlugin_msgs.msgs.ControlCommand)
}

void ControlCommand::SharedCtor() {
  ::memset(&u0l_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&u3r_) -
      reinterpret_cast<char*>(&u0l_)) + sizeof(u3r_));
}

ControlCommand::~ControlCommand() {
  // @@protoc_insertion_point(destructor:stoupentoPlugin_msgs.msgs.ControlCommand)
  SharedDtor();
}

void ControlCommand::SharedDtor() {
}

void ControlCommand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ControlCommand::descriptor() {
  ::protobuf_controlCommand_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_controlCommand_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ControlCommand& ControlCommand::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_controlCommand_2eproto::scc_info_ControlCommand.base);
  return *internal_default_instance();
}


void ControlCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 15u) {
    ::memset(&u0l_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&u3r_) -
        reinterpret_cast<char*>(&u0l_)) + sizeof(u3r_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ControlCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double u0l = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_u0l();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &u0l_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double u3l = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_u3l();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &u3l_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double u0r = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {
          set_has_u0r();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &u0r_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required double u3r = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {
          set_has_u3r();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &u3r_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:stoupentoPlugin_msgs.msgs.ControlCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:stoupentoPlugin_msgs.msgs.ControlCommand)
  return false;
#undef DO_
}

void ControlCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required double u0l = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->u0l(), output);
  }

  // required double u3l = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->u3l(), output);
  }

  // required double u0r = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->u0r(), output);
  }

  // required double u3r = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->u3r(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:stoupentoPlugin_msgs.msgs.ControlCommand)
}

::google::protobuf::uint8* ControlCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required double u0l = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->u0l(), target);
  }

  // required double u3l = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->u3l(), target);
  }

  // required double u0r = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->u0r(), target);
  }

  // required double u3r = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->u3r(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stoupentoPlugin_msgs.msgs.ControlCommand)
  return target;
}

size_t ControlCommand::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  size_t total_size = 0;

  if (has_u0l()) {
    // required double u0l = 1;
    total_size += 1 + 8;
  }

  if (has_u3l()) {
    // required double u3l = 2;
    total_size += 1 + 8;
  }

  if (has_u0r()) {
    // required double u0r = 3;
    total_size += 1 + 8;
  }

  if (has_u3r()) {
    // required double u3r = 4;
    total_size += 1 + 8;
  }

  return total_size;
}
size_t ControlCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required double u0l = 1;
    total_size += 1 + 8;

    // required double u3l = 2;
    total_size += 1 + 8;

    // required double u0r = 3;
    total_size += 1 + 8;

    // required double u3r = 4;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ControlCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const ControlCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ControlCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:stoupentoPlugin_msgs.msgs.ControlCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:stoupentoPlugin_msgs.msgs.ControlCommand)
    MergeFrom(*source);
  }
}

void ControlCommand::MergeFrom(const ControlCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      u0l_ = from.u0l_;
    }
    if (cached_has_bits & 0x00000002u) {
      u3l_ = from.u3l_;
    }
    if (cached_has_bits & 0x00000004u) {
      u0r_ = from.u0r_;
    }
    if (cached_has_bits & 0x00000008u) {
      u3r_ = from.u3r_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ControlCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControlCommand::CopyFrom(const ControlCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:stoupentoPlugin_msgs.msgs.ControlCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControlCommand::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  return true;
}

void ControlCommand::Swap(ControlCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ControlCommand::InternalSwap(ControlCommand* other) {
  using std::swap;
  swap(u0l_, other->u0l_);
  swap(u3l_, other->u3l_);
  swap(u0r_, other->u0r_);
  swap(u3r_, other->u3r_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ControlCommand::GetMetadata() const {
  protobuf_controlCommand_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_controlCommand_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace msgs
}  // namespace stoupentoPlugin_msgs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::stoupentoPlugin_msgs::msgs::ControlCommand* Arena::CreateMaybeMessage< ::stoupentoPlugin_msgs::msgs::ControlCommand >(Arena* arena) {
  return Arena::CreateInternal< ::stoupentoPlugin_msgs::msgs::ControlCommand >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
